import os as _os, sys as _sys
ROOT = _os.path.abspath(_os.path.join(_os.path.dirname(__file__), "../.."))
UPSTREAM = _os.environ.get("GG_UPSTREAM", _os.path.join(ROOT, "upstream", "grounding-gap"))
EXP = _os.path.join(UPSTREAM, "property_generation_experiments")
if not _os.path.isdir(EXP):
    _sys.exit(f"upstream repo not found at {UPSTREAM}; run scripts/setup_upstream.sh or set GG_UPSTREAM")
import sys, os, glob, ast, collections
sys.path.insert(0, EXP)
os.chdir(EXP)
import pandas as pd

gt = pd.read_csv("data/experiment_1/coding_human_ground_truth.csv")
gt["word"] = gt["word"].astype(str).str.strip().str.lower()
gt["property"] = gt["property"].astype(str).str.strip().str.lower()
gt_pairs = set(zip(gt["word"], gt["property"]))
print("expert GT (word, property) pairs:", len(gt_pairs))
print()

# Build the set of (word, property) pairs each model actually generated
models = sorted(os.listdir("coded_generations/exp1"))
rows = []
union = set()
for m in models:
    pairs = set()
    for p in glob.glob(f"coded_generations/exp1/{m}/*.csv"):
        df = pd.read_csv(p)
        for w, props in zip(df["word"], df["properties"]):
            try:
                pl = ast.literal_eval(str(props))
            except Exception:
                continue
            w = str(w).strip().lower()
            for pr in pl:
                pairs.add((w, str(pr).strip().lower()))
    union |= pairs
    inter = gt_pairs & pairs
    rows.append((m, len(pairs), len(inter), 100.0 * len(inter) / len(gt_pairs)))

rows.sort(key=lambda r: -r[3])
print(f"{'model':24s} {'its pairs':>10s} {'shared w/ GT':>13s} {'% of GT':>9s}")
print("-" * 60)
for m, n, i, pct in rows:
    print(f"{m:24s} {n:10d} {i:13d} {pct:8.1f}%")

inter_all = gt_pairs & union
print()
print(f"UNION of all 21 models: {len(union)} pairs")
print(f"GT properties found in at least one model generation: {len(inter_all)} / {len(gt_pairs)} = {100.0*len(inter_all)/len(gt_pairs):.1f}%")
print()

# how many GT properties are covered by how many distinct models
cover = collections.Counter()
per_model_pairs = {}
for m in models:
    pairs = set()
    for p in glob.glob(f"coded_generations/exp1/{m}/*.csv"):
        df = pd.read_csv(p)
        for w, props in zip(df["word"], df["properties"]):
            try:
                pl = ast.literal_eval(str(props))
            except Exception:
                continue
            w = str(w).strip().lower()
            for pr in pl:
                pairs.add((w, str(pr).strip().lower()))
    per_model_pairs[m] = pairs
for pair in gt_pairs:
    cover[sum(1 for m in models if pair in per_model_pairs[m])] += 1
print("GT properties by number of models that also generated them:")
for k in sorted(cover):
    print(f"   {k:2d} models: {cover[k]:5d} properties")

print()
print("=== sample GT rows for three words ===")
for w in ["ability", "justice", "freedom"]:
    sub = gt[gt["word"] == w]
    if len(sub):
        print(f"\n{w}:")
        for _, r in sub.iterrows():
            n_models = sum(1 for m in models if (w, r["property"]) in per_model_pairs[m])
            print(f"   {r['property']:24s} {r['label']:14s} generated by {n_models:2d}/21 models")
